# Generated by Django 4.1.2 on 2022-12-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_banner',
        ),
    ]
