# Generated by Django 4.1.2 on 2023-01-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_remove_profile_profile_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
