# Generated by Django 4.1.2 on 2022-11-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone No')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('message_date', models.DateField(verbose_name='Message Date')),
                ('message', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Help',
                'verbose_name_plural': 'Helps',
                'ordering': ['-message_date'],
            },
        ),
    ]
