# Generated by Django 4.1.2 on 2022-11-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notes', 'verbose_name_plural': 'Notes'},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='User',
            new_name='user',
        ),
    ]
